Repository gdsc-gvp/Pyscripts, pull requests merged in 2021-10, with the labels that each got.

#3 Create community.yml
  .github/workflows/community.yml
Labels: enhancement, Hacktoberfest, Hacktoberfest-accepted

#6 Create Flag_using_turtle.py
  Flag/Flag_using_turtle.py
Labels: Hacktoberfest, Hacktoberfest-accepted, approved

#8 Created Web Scraping
  Web Scraping/Web_Scraping.py
Labels: Hacktoberfest, Hacktoberfest-accepted, approved

#12 created turtle.py
  Pattern using turtle/Turtle.py
Labels: Hacktoberfest, Hacktoberfest-accepted, approved

#14 added pomodoro program
  pomodoro/pomo.py
Labels: Hacktoberfest-accepted, approved

#18 Added Snake Game based on issue #15
  Snake Game .py/data.txt
  Snake Game .py/food.py
  Snake Game .py/main.py
  Snake Game .py/scoreboard.py
  Snake Game .py/snake.py
Labels: Hacktoberfest, Hacktoberfest-accepted, approved
